### ISSUE TITLE
Map Package problem

### ISSUE THREAD

**Issue by AliHamed195** [Hass-Ali-Collabs/NetMo#1]
I have a problem in "pyqtMap" branch exactly in the pyMap.py file. 
I had a problem getting this code to work due to it not accepting "PyQt5.QtWebEngineWidgets" package, I tried deleting the file and downloading it again, but the problem persists.

**Comment by Hass-seen** [comment]
unfortunately compatibility issues are plaguing my code too, i face issues with Pyshark incompatibility with windows, i couldn't role back to the previous version that worked with windows i just had to rethink the way i was approaching the whole program

**Comment by AliHamed195** [comment]
the problem has been solved
